"""empty message

Revision ID: 930cbe35c912
Revises: 3b21e50003ec
Create Date: 2017-11-04 06:44:12.687882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930cbe35c912'
down_revision = '3b21e50003ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
