"""empty message

Revision ID: dc54bdfb83cd
Revises: 3e5faebe43a3
Create Date: 2017-10-04 11:07:53.868274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc54bdfb83cd'
down_revision = '3e5faebe43a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_public_id_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_public_id_key', 'users', ['public_id'])
    # ### end Alembic commands ###
